name: 📗 Open an issue regarding the Domino docs
description: Let us know about any problematic API reference documents
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for wanting to make Domino better!
        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Affected URL(s)
  - type: textarea
    attributes:
      label: Description of the problem
    validations:
      required: true